# workflow for execute a terraform deployment for vault conf
name: vault-terra
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
      - name: Terraform Init
        run: terraform init -backend-config backend/backend.hcl
      - name: Terraform plan
        run: terraform plan 
        env:
           TF_VAR_token: ${{ secrets.TOKEN }}
           TF_VAR_secret_example: ${{ secrets.SECRET_EXAMPLE }}
           ARM_ACCESS_KEY : ${{ secrets.SA_ACCES_KEY }}
    
    #   - name: Terraform Apply
    #     run: terraform apply -auto-approve
    #     env:
    #       VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
    #       VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
    #       TF_VAR_token: ${{ secrets.TF_VAR_token }}
    #       TF_VAR_secret_example: ${{ secrets.TF_VAR_secret_example }}
    
